# GitHub already does this for us...
use_directory_urls: false


theme: 
  name: material
  custom_dir: ../../extras

  features:
    - toc.integrate
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - assets/css/selecting.css
  - assets/css/custom.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details

plugins:
  - include-markdown:
      dedent: true
